<div id="previa-tiques" class="modal">
    <div class="modal-background"></div>
    <div class="modal-card">
        <header class="modal-card-head">
            <p class="modal-card-title">Confirmación</p>
            <button class="delete" aria-label="close"></button>
        </header>
        <section class="modal-card-body">
            <!-- Content ... -->
            <div class="columns has-text-black">
                <div class="column pl-6">
                    <p class="is-text"><b class="mr-2">Rut:</b>  <span id="prev-rut"></span></p>
                    <p class="is-text"><b class="mr-2">Nombre:</b>  <span id="prev-nombre"></span></p>
                    <p class="is-text"><b class="mr-2">Apellido:</b>  <span id="prev-apellido"></span></p>
                    <p class="is-text"><b class="mr-2">Fecha Nacimiento:</b>  <span id="prev-fecha"></span></p>
                    <p class="is-text"><b class="mr-2">Teléfono:</b>  <span id="prev-telefono"></span>
                    <p class="is-text"><b class="mr-2">Correo:</b>  <span id="prev-correo"></span></p>
                </div>
                <div class="column pl-6">
                    <p class="is-text"><b class="mr-2">Criticidad:</b>  <span id="prev-criticidad"></span>
                    <p class="is-text"><b class="mr-2">Tipo Tique:</b>  <span id="prev-tipo-tique"></span></p>
                    <p class="is-text"><b class="mr-2">Area:</b>  <span id="prev-area"></span>
                </div>
            </div>
            <div class="pl-5">
                <div class="has-text-black pl-3 mb-4">
                    <p class="is-text has-text-weight-bold">Detalle Problema</p>
                    <p id="prev-problema" class="is-text"></p>
                </div>
                <div class="has-text-black pl-3">
                    <p class="is-text has-text-weight-bold">Detalle Servicio</p>
                    <p id="prev-servicio" class="is-text"></p>
                </div>
            </div>
        </section>
        <footer class="modal-card-foot">
            <button class="button is-success rut-btn-verify" data-target="rut-2">Aceptar</button>
            <button class="button">Editar</button>
        </footer>
    </div>
</div>
<script src="<?=BASE_URL?>/js/modal/modals-info.js?t=1491313943549"></script>