<?php
/** @var $tiqueStats */
?>

<div id="jefe-mesa-dashboard">
    <h2 class="title has-text-black">Dashboard</h2>
    <div class="is-flex charts-container is-justify-content-center mb-5">
        <div class="canvas-charts force-chart-full-width">
            <canvas id="myChart"></canvas>
        </div>
    </div>
    <div class="pl-5 mt-4 pt-3">
        <h2 class="title">Total Tiques: <?=$tiqueStats['totalTiques']?></h2>
    </div>

</div>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    const labels = <?php echo json_encode($tiqueStats['meses'])?>;
    const data = {
        labels: labels,
        datasets: [{
            label: 'Tiques creados',
            data: <?php echo json_encode($tiqueStats['data'])?>,
            fill: false,
            borderColor: 'rgb(75, 192, 192)',
            tension: 0.1,
        }]
    };
</script>
<script>
    const config = {
        type: 'line',
        data: data,
    };

    let myChart = new Chart(
        document.getElementById('myChart'),
        config
    );
</script>
