<?php




?>


<footer class="has-background-grey-dark">
    <div class="p-4  is-flex is-flex-direction-column is-align-items-center">
        <div class="is-inline-block">
            <span class="title has-text-grey-lighter pb-4">&copy; <?=date('Y')?> CONSÚLTENOS</span>
        </div>
        <div class="is-inline-block">
            <span class="has-text-white is-size-7">Powered by <b>Benjabot Svcs</b></span>
        </div>
    </div>
</footer>

</body>
</html>
