<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Sistema Tiques</title>
    <link rel="stylesheet" href="<?=BASE_URL?>/css/bulma.css">
    <link rel="stylesheet" href="<?=BASE_URL?>/css/mystyles.css?t=<?=time()?>">
    <script src="<?=BASE_URL?>/js/modal/modal.js?t=<?=time()?>"></script>
    <script src="https://kit.fontawesome.com/81bf225702.js" crossorigin="anonymous"></script>
    <script src="<?=BASE_URL?>/js/validations/validations.js?t=<?=time()?>"></script>
    <link rel="icon" type="image/svg+xml" href="favicon.svg" />

</head>
<body>
<nav class="navbar has-background-grey-darker pl-4 pr-4" role="navigation" aria-label="main navigation">
    <?php if(isset($_SESSION['user'])):?>
    <div class="navbar-brand is-justify-content-space-between">
        <a class="navbar-item is-white">
            <span class="icon"><i class="fa-solid fa-user icon mt-2 icon-white"></i></span>
        </a>
        <a role="button" class="navbar-item is-hidden-desktop is-hidden-widescreen is-right button" href="<?=BASE_URL.'/admin-home/cerrar'?>" aria-expanded="false" data-target="navbarBasicExample">
            <span>SALIR</span>
        </a>
    </div>
    <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
            <a class="navbar-item icon-custom cancel-hover mr-2">
                <div class="is-size-7">
                    <span class="is-underlined">Usuario:</span> <?=$_SESSION['user']['nombreCompleto'] ?>
                </div>
                <div class="is-size-7">
                    <span class="is-underlined">Área:</span> <?=$_SESSION['user']['nombreArea']?>
                </div>
            </a>
        </div>

        <div class="navbar-end">
            <a class="navbar-item icon-custom cancel-hover mr-2">
                <div class="is-size-5">
                    <span class="is-underlined"></span> <?=$_SESSION['user']['nombreTipo'] ?>
                </div>
            </a>
            <div class="navbar-item">
                <div class="buttons">
                    <a href="<?=BASE_URL.'/admin-home/cerrar'?>" class="button is-light">
                        Salir
                    </a>
                </div>
            </div>
        </div>
    </div>
    <?php endif;?>
</nav>